### ISSUE TITLE
Mechanism for automatically fetching secrets

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#13]
When a task needs to use a secret, we need to create a custom wrapper script that first downloads the secret from the secrets service, sets it up, and then invokes the regular command. This makes creating tasks that need secrets inconvenient.. There's no way to just "declare" that the secret is needed in the task definition and have everything just work.

I propose we introduce a new run-task based mechanism for handling secrets. At a high level it would work like this:

1. A task declares which secrets it needs in a top-level `secrets` key.
2. The `run_task.py` transforms would massage this into a format we can easily stuff into an environment variable.
3. The `run-task` script reads said env and fetches the required secrets before proceeding with the task

There is precedent here as this is exactly how `fetches` work.

To start, the schema for defining the `secrets` should support both environment variables, as well as files. Maybe something like:
```
secrets:
    - secret: myproject/secret
      key: api_token
      env: API_TOKEN
    - secret: myproject/other/secret
      file: /builds/worker/secret
```

The above definition would:
A) store the value of `api_token` in the `myproject/secret` secret into the `API_TOKEN` env
B) write the entirety of the `myproject/other/secret` secret wholesale into a file at `/builds/worker/secret`
