### ISSUE TITLE
Provide more defaults for kinds

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskgraph#184]
One of the bigger barriers to using taskgraph is how intimidating it is to write configs. One particular part of this is how much there often is in a `kind` that doesn't directly relate to the task being written, or is essentially boilerplate that most kinds need. As a concrete example, this is a current `kind` definition used by MozillaVPN:
```
loader: taskgraph.loader.transform:loader

transforms:
    - taskgraph.transforms.job:transforms
    - taskgraph.transforms.task:transforms

tasks:
    taskgraph-definition:
        worker-type: b-linux
        worker:
            docker-image: {in-tree: base}
            max-run-time: 3600
        description: "Test the full `mozilla_vpn_taskgraph` to validate the latest changes"
        treeherder:
            symbol: test-taskgraph-definition
            kind: test
            platform: tests/opt
            tier: 1
        run:
            using: run-task
            use-caches: true
            cwd: '{checkout}'
            command: >-
                pip3 install -r taskcluster/requirements.txt &&
                taskgraph full --p taskcluster/test/params &&
                taskgraph full
```

The entirity of the `loader` and `transforms` keys are boilerplate, as well as much of the `run` section. Many other parts would be unnecessary if we provided better defaults in the `job` and/or `task` transforms. In the end, I think it's possible to shrink the above down to:
```
tasks:
    taskgraph-definition:
        worker:
            docker-image: {in-tree: base}
        description: "Test the full `mozilla_vpn_taskgraph` to validate the latest changes"
        run:
            command: >-
                pip3 install -r taskcluster/requirements.txt &&
                taskgraph full --p taskcluster/test/params &&
                taskgraph full

```

...at which point, the entire `kind` is something that I think we could reasonable expect a project owner to understand and write.

Concretely, I suggest we make the following changes:
* Use the `transform` loader as the default loader
* Provide the `job` and `task` transforms as the default transforms for the `transform` loader.
* Provide smart defaults for the entirety of the `treeherder` section:
  * Use the capitalized first letter of the `kind` for `symbol` (if multiple kinds share the same first letter, take the first two -- but after that make it required).
  * `kind` can obviously be trivially filled out
  * `tier` can default to 1
  * `platform` can default to the job/task name within the `kind`
* Parts of `worker` can have defaults as follows:
  * `chain-of-trust` defaults to `true`
  * `taskcluster-proxy` defaults to `true` (unless this is a security risk for a reason I'm unaware of)
  * `max-run-time` can default to some value (I'll throw out `1800`, but I have no real strong opinion)
  * `artifacts` should use the more or less standard entry of
```
        artifacts:
            - type: directory
              name: public/build
              path: /builds/worker/artifacts
```
* `run` can also provide a number of defaults
  * `using` can be `run-task`
  * `use-caches` can be `true`
  * `cwd` can be `{checkout}`
  * `worker-type` can be `b-linux`
    * I could be convinced this is a bad idea - but I _think_ it's true that unless you're building for Windows or macOS, your task is probably running on Linux.

Because these changes will be making many things implicit where they used to be explicit, we _must_ (as in, do not land without this) update the docs with better reference information if/when we do this. The goal here is to provide very sensible _defaults_ to lower the learning curve to adopting taskgraph (and by extension, Taskcluster) -- we do _not_ want to make it more difficult to use a more sophisticated configuration as projects outgrow early simplicity.
