### ISSUE TITLE
Allow setting level 3 task-expires-after in the graph configuration

### ISSUE THREAD

**Issue by gabrielBusta** [taskcluster/taskgraph#410]
The way the graph config could look like:

```yaml
task-expires-after:
    by-level:
        1: 90 days
        3: 1 year
```

We could set a single default for all levels:

```yaml
task-expires-after: 1 year
```
