### ISSUE TITLE
translations_taskgraph.util.dict_helpers.deep_get doesn't support lists

### ISSUE THREAD

**Issue by gregtatum** [taskcluster/taskgraph#665]
I have some configs that use lists in the yaml files, that I'd like to build kinds from. Currently `deep_get` doesn't support lists. I would expect the `[0]` syntax to work, or alternately a `.0` would work, but the function uses a dict .get method, which isn't support by lists.

```yaml
tasks:
    teacher-{src_locale}-{trg_locale}-1:
        task-context:
            from-parameters:
                url_prefix: training_config.continuation.models.teacher.urls[0]
    teacher-{src_locale}-{trg_locale}-2:
        task-context:
            from-parameters:
                url_prefix: training_config.continuation.models.teacher.urls[1]
```
